### ISSUE TITLE
How can i use the Webdriver commands ? 

### ISSUE THREAD

**Issue by johnny-shrewd** [Matt-B/cucumber-js-selenium-webdriver-example#6]
I want to be able to use the commends from the webdriver api ( http://webdriver.io/api.html ) like browser.getUrl() .... how or what do i need to modify to be able to use that instead of driver.

**Comment by Matt-B** [comment]
Hi!

At the moment this project uses the Selenium Project JavaScript bindings (npm package: selenium-webdriver), rather than webdriver.io (npm package: webdriverio), so you'd need to swap those over in order to use the API calls referenced in the page you linked. There's not much code here so a swap shouldn't be hard. Broadly, you'd want to add webdriverio to the package.json, remove selenium-webdriver, and amend any code in steps and hooks that interacts with the browser.

Hope that helps - let me know if you have any questions.

Matt
